### PR TITLE
New training material for publishing CDK construct using projen + jsii

### PR DESCRIPTION
**Pull request by seeebiii**
See diff :-)

## Requirements for your pull request

- Use the following format: `[library](link) - Description.`
- The text of the link should be the name of the package or project.
- If you add a construct published in multiple languages via JSII, the link should point to the source repository, not to npm, PyPI etc
- Add one link per pull-request.
- Keep descriptions concise, clear and simple, and end them with a period / stop.
- New categories, or improvements to the existing ones are also welcome.
- Make sure your text editor is set to remove trailing whitespace.
- It is desirable for the whole thing to fit on one line after getting rendered by GitHub.

### CODE REVIEW

**Comment by seeebiii** [comment]
Let me know what I should do with the failing lint check...  I'd like to keep the link to `jsii` but if that's a blocker, I can remove it.

**Comment by kolomied** [comment]
@seeebiii  Do you mind installing [awesome-lint](https://github.com/sindresorhus/awesome-lint) and run the tests locally? I see the following error:

```
> awesome-cdk@ test /home/runner/work/awesome-cdk/awesome-cdk
> awesome-lint

- Linting
✖ Linting

  readme.md:112:246
  ✖  112:246  https://github.com/aws/jsii  remark-lint:double-link
  ✖  134:225  https://github.com/aws/jsii  remark-lint:double-link
```

**Comment by seeebiii** [comment]
@kolomied I know, I've seen the error in GitHub Action. It's because the link to `jsii` is already present as a separate link and I link to it in the description to my link... I'll then simply remove it

**Review by kolomied — APPROVED** [review]

**Comment by kolomied** [comment]
@seeebiii Merged - sorry for the delay and thank you for the contribution! 👍

**Comment by seeebiii** [comment]
No worries @kolomied - thanks for merging :-)

**Pull request merged**
